### ISSUE TITLE
Front-end / back-end desynchronization

### ISSUE THREAD

**Issue by pvh** [automerge/automerge#172]
Haven't had much time to look into this yet, but I'm seeing these intermittently in pushpin (as are other users) and wondered if @ept has any immediate ideas about what to check:

```
C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307 Uncaught RangeError: Mismatched sequence number: patch 3 does not match next request 2
    at Object.applyPatch (C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307:15)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:167:29)
    at DocFrontend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:185:5)
    at DocFrontend.patch (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:165:10)
    at RepoFrontend.receive (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoFrontend.ts:248:17)
    at Queue.back.subscribe.msg (webpack-internal:///./src/renderer/index.js:85:31)
    at DocBackend.RepoBackend.documentNotify [as notify] (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoBackend.ts:312:25)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:192:14)
    at DocBackend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:207:5)
    at Queue.localChangeQ.subscribe.change (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:187:12)
applyPatch @ C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:65
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:151
DocFrontend.patch @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:63
RepoFrontend.receive @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoFrontend.js:200
back.subscribe.msg @ index.js?ce91:55
RepoBackend.documentNotify @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoBackend.js:148
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:144
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:158
localChangeQ.subscribe.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:139
DocBackend.applyLocalChange @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:55
RepoBackend.receive @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoBackend.js:336
front.subscribe.msg @ index.js?ce91:56
changeQ.subscribe.fn @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:133
DocFrontend.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:39
Handle.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\Handle.js:71
Share._defineProperty @ share.js?3f92:96
Share.doc @ share.js?3f92:54
boardHandle.window.repo.watch.doc @ share.js?3f92:49
Handle.push @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\Handle.js:17
handles.forEach.handle @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:111
newState @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:110
changeQ.subscribe.fn @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:132
DocFrontend.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:39
Handle.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\Handle.js:71
Board._defineProperty @ board.js?87a5:431
Board._defineProperty @ board.js?87a5:417
_hyperfile__WEBPACK_IMPORTED_MODULE_11__.writeBuffer @ board.js?87a5:371
writeBuffer @ hyperfile.js?95aa:39
Board._defineProperty @ board.js?87a5:365
reader.onload @ board.js?87a5:207
load (async)
Board.e @ board.js?87a5:206
callCallback @ react-dom.development.js?61bb:149
invokeGuardedCallbackDev @ react-dom.development.js?61bb:199
invokeGuardedCallback @ react-dom.development.js?61bb:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?61bb:270
executeDispatch @ react-dom.development.js?61bb:561
executeDispatchesInOrder @ react-dom.development.js?61bb:583
executeDispatchesAndRelease @ react-dom.development.js?61bb:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js?61bb:688
forEachAccumulated @ react-dom.development.js?61bb:662
runEventsInBatch @ react-dom.development.js?61bb:816
runExtractedEventsInBatch @ react-dom.development.js?61bb:824
handleTopLevel @ react-dom.development.js?61bb:4826
batchedUpdates$1 @ react-dom.development.js?61bb:20439
batchedUpdates @ react-dom.development.js?61bb:2151
dispatchEvent @ react-dom.development.js?61bb:4905
(anonymous) @ react-dom.development.js?61bb:20490
unstable_runWithPriority @ scheduler.development.js?3069:255
interactiveUpdates$1 @ react-dom.development.js?61bb:20489
interactiveUpdates @ react-dom.development.js?61bb:2170
dispatchInteractiveEvent @ react-dom.development.js?61bb:4882
C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307 Uncaught RangeError: Mismatched sequence number: patch 4 does not match next request 2
    at Object.applyPatch (C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307:15)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:167:29)
    at DocFrontend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:185:5)
    at DocFrontend.patch (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:165:10)
    at RepoFrontend.receive (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoFrontend.ts:248:17)
    at Queue.back.subscribe.msg (webpack-internal:///./src/renderer/index.js:85:31)
    at DocBackend.RepoBackend.documentNotify [as notify] (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoBackend.ts:312:25)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:192:14)
    at DocBackend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:207:5)
    at Queue.localChangeQ.subscribe.change (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:187:12)
applyPatch @ C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:65
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:151
DocFrontend.patch @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:63
RepoFrontend.receive @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoFrontend.js:200
back.subscribe.msg @ index.js?ce91:55
RepoBackend.documentNotify @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoBackend.js:148
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:144
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:158
localChangeQ.subscribe.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:139
DocBackend.applyLocalChange @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:55
RepoBackend.receive @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoBackend.js:336
front.subscribe.msg @ index.js?ce91:56
changeQ.subscribe.fn @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:133
DocFrontend.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:39
Handle.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\Handle.js:71
Board._defineProperty @ board.js?87a5:487
cards.forEach.card @ board.js?87a5:783
Board._defineProperty @ board.js?87a5:772
BoardCard.onStop @ board-card.js?011a:18
DraggableCore._this.handleDragStop @ react-draggable.js?d358:1642
C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307 Uncaught RangeError: Mismatched sequence number: patch 5 does not match next request 2
    at Object.applyPatch (C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307:15)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:167:29)
    at DocFrontend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:185:5)
    at DocFrontend.patch (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:165:10)
    at RepoFrontend.receive (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoFrontend.ts:248:17)
    at Queue.back.subscribe.msg (webpack-internal:///./src/renderer/index.js:85:31)
    at DocBackend.RepoBackend.documentNotify [as notify] (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoBackend.ts:312:25)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:192:14)
    at DocBackend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:207:5)
    at Queue.localChangeQ.subscribe.change (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:187:12)
applyPatch @ C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:65
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:151
DocFrontend.patch @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:63
RepoFrontend.receive @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoFrontend.js:200
back.subscribe.msg @ index.js?ce91:55
RepoBackend.documentNotify @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoBackend.js:148
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:144
bench @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:158
localChangeQ.subscribe.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:139
DocBackend.applyLocalChange @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocBackend.js:55
RepoBackend.receive @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\RepoBackend.js:336
front.subscribe.msg @ index.js?ce91:56
changeQ.subscribe.fn @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:133
DocFrontend.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\DocFrontend.js:39
Handle.change @ C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\dist\Handle.js:71
Board._defineProperty @ board.js?87a5:487
cards.forEach.card @ board.js?87a5:783
Board._defineProperty @ board.js?87a5:772
BoardCard.onStop @ board-card.js?011a:18
DraggableCore._this.handleDragStop @ react-draggable.js?d358:1642
C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307 Uncaught RangeError: Mismatched sequence number: patch 6 does not match next request 2
    at Object.applyPatch (C:\Users\Peter\Dev\pushpin\node_modules\automerge\frontend\index.js:307:15)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:167:29)
    at DocFrontend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:185:5)
    at DocFrontend.patch (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocFrontend.ts:165:10)
    at RepoFrontend.receive (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoFrontend.ts:248:17)
    at Queue.back.subscribe.msg (webpack-internal:///./src/renderer/index.js:85:31)
    at DocBackend.RepoBackend.documentNotify [as notify] (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\RepoBackend.ts:312:25)
    at bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:192:14)
    at DocBackend.bench (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:207:5)
    at Queue.localChangeQ.subscribe.change (C:\Users\Peter\Dev\pushpin\node_modules\hypermerge\src\DocBackend.ts:187:12)
```

**Comment by ept** [comment]
Every change generated by the frontend needs to make a round-trip through the backend before it is fully complete. These changes need to be processed in-order (they may be interspersed with remote patches that came in over the network, but the responses from the backend to the frontend need to be in the same order as the requests were sent from the frontend to the backend).

Here it looks like change number 2 did not complete the round-trip: the frontend received numbers 3, 4, 5 and 6 when it was expecting 2. Maybe change 2 was dropped somewhere due to a different exception?

**Comment by ept** [comment]
Closing this issue as there hasn't been any update in a long time.
