### ISSUE TITLE
Missing index entry for list element

### ISSUE THREAD

**Issue by nornagon** [automerge/automerge#234]
I'm not quite sure how I managed to produce this issue, but by some combination of `insertAt` and `deleteAt` in a single `Automerge.Text` object I produced two documents that throw an exception when I try to apply changes from one to the other.

Repro: [repro.zip](https://github.com/automerge/automerge/files/4301454/repro.zip)

```
/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:465
        throw _iteratorError6;
        ^

TypeError: Missing index entry for list element b13248e6-aa9e-419a-9099-59c3b3380d7c:255
    at getParent (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:1377:25)
    at getPrevious (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:1423:18)
    at updateListElement (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:929:16)
    at applyAssign (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:1060:12)
    at applyOps (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:1124:28)
    at applyChange (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:1193:19)
    at applyQueuedOps (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:1226:30)
    at Object.addChange (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:1310:12)
    at apply (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:424:36)
    at Object.applyChanges (/Users/nornagon/Source/autowiki/node_modules/automerge/dist/automerge.js:481:10)
```

**Comment by ept** [comment]
Somehow you ended up in a state where the two documents contain different changes under the same actorId and sequence number:

```js
Automerge.getAllChanges(doc1).find(change => change.actor === 'b13248e6-aa9e-419a-9099-59c3b3380d7c' && change.seq === 54)
/* { ops:
   [ { action: 'ins',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:230',
       elem: 255 },
     { action: 'set',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:255',
       value: 'g' } ],
  actor: 'b13248e6-aa9e-419a-9099-59c3b3380d7c',
  seq: 54,
  deps: {} } */

Automerge.getAllChanges(doc2).find(change => change.actor === 'b13248e6-aa9e-419a-9099-59c3b3380d7c' && change.seq === 54)
/* { ops:
   [ { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:231' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:232' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:233' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:234' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:235' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:236' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:237' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:238' },
     { action: 'del',
       obj: 'bb49183a-c8aa-40b7-99a4-805c98635b3b',
       key: 'b13248e6-aa9e-419a-9099-59c3b3380d7c:239' } ],
  actor: 'b13248e6-aa9e-419a-9099-59c3b3380d7c',
  seq: 54,
  deps: {} } */
```

Automerge currently does not detect this inconsistency, and so the problem only shows up later, when trying to refer to an element that was inserted in doc1's history, but is missing from doc2's history.

You might have ended up in this state because two different processes were using the same actorId, or maybe if a process crashed before saving its state to disk, and then reused the same actorId after recovering from the crash.
