### ISSUE TITLE
Can't apply changes to clone

### ISSUE THREAD

**Issue by rongoro** [automerge/automerge#500]
I'm trying to apply a set of changes to a clone of a document. They apply fine to the loaded original fine, but fail with an exception when applied to a clone of the loaded doc. I was originally using preview.7 but run into the same failure with the latest checkout (the exception below is from the latest checkout).

The reason I'm doing this is that I need to apply changes and then see if the doc has changed (I compare the heads). If it hasn't changed I want to keep the original doc in place. But by applying the changes it marks the original doc as frozen. So I thought cloning the original doc and then applying the changes would be a simple way around the problem.

```
const Automerge = require("./automerge");

const origDoc = { a: ["foo"] };
const doc = Automerge.from(origDoc);

const doc2 = Automerge.change(doc, (d) => {
  d.a.push("foo");
});

const changes = Automerge.getAllChanges(doc2);

const doc2save = Automerge.save(doc2);

const doc2load = Automerge.load(doc2save);

const doc2clone = Automerge.clone(doc2load);

// const changesAppliedDoc2 = Automerge.applyChanges(doc2, changes);
// console.log(changesAppliedDoc2);

const changesAppliedDoc2clone = Automerge.applyChanges(doc2clone, changes);
console.log(changesAppliedDoc2clone);
```

```
/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:1142
    let left = 0, right = actorChanges.length
                                       ^

TypeError: Cannot read property 'length' of undefined
    at groupChangeOps (/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:1142:40)
    at decodeDocument (/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:1270:3)
    at decodeChanges (/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:1074:34)
    at BackendDoc.computeHashGraph (/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:4439:24)
    at BackendDoc.applyChanges (/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:4380:14)
    at Object.applyChanges (/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:48:23)
    at Object.applyChanges (/home/ron/Development/GoodCTZN/automerge/dist/automerge.js:15126:37)
    at Object.<anonymous> (/home/ron/Development/GoodCTZN/automerge/dist/test.js:21:43)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by rongoro** [comment]
yeah, looks like #502 fixes the issue I was seeing. Thanks!
