### ISSUE TITLE
Calling applyChanges twice with unresolved dependencies throws and exception

### ISSUE THREAD

**Issue by jimpick** [automerge/automerge#65]
I've attached a PR #64 

Here is an example:

```js
const Automerge = require('automerge')

const alice1 = Automerge.init('alice')

const alice2 = Automerge.change(alice1, doc => {
  doc.test = 'a'
})

const aliceChanges1to2 = Automerge.getChanges(alice1, alice2)
console.log('Alice 1 to 2 changes %o', aliceChanges1to2)

const alice3 = Automerge.change(alice2, doc => {
  doc.test = 'b'
})

const aliceChanges2to3 = Automerge.getChanges(alice2, alice3)
console.log('Alice 2 to 3 changes %o', aliceChanges2to3)

const alice4 = Automerge.change(alice3, doc => {
  doc.test = 'c'
})

const aliceChanges3to4 = Automerge.getChanges(alice3, alice4)
console.log('Alice 3 to 4 changes %o', aliceChanges3to4)

const bob1 = Automerge.init('bob')

const bob2 = Automerge.applyChanges(bob1, aliceChanges3to4)

console.log('bob2', bob2)

const bob3 = Automerge.applyChanges(bob2, aliceChanges2to3)

// Boom!
```

```
$ node simpler.js 
Alice 1 to 2 changes [ { actor: 'alice',
    seq: 1,
    deps: {},
    message: undefined,
    ops: 
     [ { action: 'set',
         obj: '00000000-0000-0000-0000-000000000000',
         key: 'test',
         value: 'a' },
       [length]: 1 ] },
  [length]: 1 ]
Alice 2 to 3 changes [ { actor: 'alice',
    seq: 2,
    deps: {},
    message: undefined,
    ops: 
     [ { action: 'set',
         obj: '00000000-0000-0000-0000-000000000000',
         key: 'test',
         value: 'b' },
       [length]: 1 ] },
  [length]: 1 ]
Alice 3 to 4 changes [ { actor: 'alice',
    seq: 3,
    deps: {},
    message: undefined,
    ops: 
     [ { action: 'set',
         obj: '00000000-0000-0000-0000-000000000000',
         key: 'test',
         value: 'c' },
       [length]: 1 ] },
  [length]: 1 ]
bob2 { _objectId: '00000000-0000-0000-0000-000000000000' }
/Users/jim/tmp/break-automerge/node_modules/automerge/src/freeze_api.js:221
  Object.assign(Object.getPrototypeOf(rootObj), {_state: state, _actorId: state.get('actorId')})
         ^

TypeError: Cannot assign to read only property '_state' of object '#<Object>'
    at Function.assign (<anonymous>)
    at rootObject (/Users/jim/tmp/break-automerge/node_modules/automerge/src/freeze_api.js:221:10)
    at Object.applyChanges (/Users/jim/tmp/break-automerge/node_modules/automerge/src/freeze_api.js:249:10)
    at Object.applyChanges (/Users/jim/tmp/break-automerge/node_modules/automerge/src/auto_api.js:47:22)
    at Object.<anonymous> (/Users/jim/tmp/break-automerge/simpler.js:32:24)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by ept** [comment]
Fixed in #64.
