### ISSUE TITLE
Automerge.Text serialization fails with large strings

### ISSUE THREAD

**Issue by imathews** [automerge/automerge#756]
There is an issue in https://github.com/automerge/automerge-classic/issues/499, which is still present on the latest version of Automerge, where initializing `Text()` with a large string throws a max call stack exception. Similar errors are thrown if calling `Text.insertAt(index, ...longString)`. 

To work around this, I attempted to insert the text in chunks. Basically:
```js
function insertString(currentText, str){
    const maxInsertSize = 10000;
    for (let i = 0; i < str.length; i += maxInsertSize) {
         currentText.insertAt( i, ...str.slice(i, i + maxInsertSize));
    }
}
```

This doesn't throw any errors on insertion; however, an error is thrown at the end of the `Automerge.change()` callback. Specifically: 
```js
const longString = 'some long string';
let currentDocument = Automerge.init();
const newDoc = Automerge.change(currentDocument, (doc) => {
    doc.str = new Automerge.Text();
    insertString(doc.str, longString);
    
    console.log('inserted successfully!'); // this prints to console
});
console.log('got newDoc') // We never make it to this line, the error is thrown in Automerge.change()
```
The error I'm getting is below. This is happening for strings > 130k characters, but works fine at 100k, though I didn't determine the exact threshold.
```
'error calling splice: JsValue(RangeError: Maximum call stack size exceeded\n' +
      'RangeError: Maximum call stack size exceeded\n' +
      '    at /app/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1829:25\n' +
      '    at handleError (/app/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:392:18)\n' +
      '    at module.exports.__wbg_apply_f9ecfcbfefaf7349 (/app/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1828:67)\n' +
      '    at js_sys::Reflect::apply::h51cfd424a68a6c78 (wasm://wasm/0061ed76:wasm-function[1539]:0x149238)\n' +
      '    at automerge_wasm::interop::<impl automerge_wasm::Automerge>::apply_patch_to_array::h5ab9ef8e4d7d6c2f (wasm://wasm/0061ed76:wasm-function[136]:0x74028)\n' +
      '    at automerge_wasm::interop::<impl automerge_wasm::Automerge>::apply_patch::h3a6594c8697a8bdd (wasm://wasm/0061ed76:wasm-function[146]:0x7e5f6)\n' +
      '    at automerge_wasm::interop::<impl automerge_wasm::Automerge>::apply_patch::h3a6594c8697a8bdd (wasm://wasm/0061ed76:wasm-function[146]:0x7dc96)\n' +
      '    at automerge_wasm::interop::<impl automerge_wasm::Automerge>::apply_patch::h3a6594c8697a8bdd (wasm://wasm/0061ed76:wasm-function[146]:0x7dc96)\n' +
      '    at automerge_wasm::interop::<impl automerge_wasm::Automerge>::apply_patch::h3a6594c8697a8bdd (wasm://wasm/0061ed76:wasm-function[146]:0x7dc96)\n' +
      '    at automerge_wasm::Automerge::apply_patches_impl::h9e302b456c15bb97 (wasm://wasm/0061ed76:wasm-function[282]:0xc7731))'
```

**Comment by nyan-left** [comment]
I've found that if you add a small delay between the insertion iterations it doesn't throw with `Maximum call stack size exceeded`.

```ts
async function insertString(currentText, str){
    const maxInsertSize = 10000;
    for (let i = 0; i < str.length; i += maxInsertSize) {
         currentText.insertAt( i, ...str.slice(i, i + maxInsertSize));
        await delay(0)
    }
}
```
