### ISSUE TITLE
wasm.__wbindgen_add_to_stack_pointer is not a function

### ISSUE THREAD

**Issue by Sjoerd82** [automerge/automerge#788]
I just started playing with Automerge. I am looking to see if it can bring CRDT's to my offline-first app! This is a Quasar project, so everything is always a little different. I'm using the Quasar 2, Vue3, TS, Vite 2.

My code is basically just one of the examples.

In installed Automerge `yarn add @automerge/automerge @automerge/automerge-repo`. When I got an WASM-sounding error, I also added `yarn add vite-plugin-wasm`.I've never worked with WASM, and honestly, don't really understand how it works.

The code:
```ts
import {next as A} from '@automerge/automerge'

export function _testAm() {
    let doc = A.from({
        map: { 
            key: 'value',
            nested_map: {key: 'value'},
            nested_list: [1],
        },
        list: ['a', 'b', 'c', {nested: 'map'}, ['nested list']],
        // Note we are using the `next` API for text, so text sequences are strings
        text: 'some text',
        // In the `next` API non mergable strings are instances of `RawString`.
        // You should generally not need to use these. They are retained for backwards
        // compatibility
        raw_string: new A.RawString('rawstring'), 
        integer: 1,
        float: 2.3,
        boolean: true,
        bytes: new Uint8Array([1, 2, 3]),
        date: new Date(),
        counter: new A.Counter(1),
        none: null,
    })

    doc = A.change(doc, d => {
        // Insert 'Hello' at the begnning of the string
        A.splice(d, ['text'], 0, 0, 'Hello ')
        d.counter.increment(20)
        d.map.key = 'new value'
        d.map.nested_map.key = 'new nested value'
        d.list[0] = 'A'
        d.list.insertAt(0, 'Z')
        d.list[4].nested = 'MAP'
        d.list[5][0] = 'NESTED LIST'
    })
    
    console.log(doc)
}
```

It fails on `A.from(` with the error `wasm.__wbindgen_add_to_stack_pointer is not a function`.

I suspect maybe it's a Vite and/or WASM issue.. Does this error mean anything to anyone?

**Comment by alexjg** [comment]
Yeah this usually occurs when the wasm has not initialized for one reason or another. Could you post the vite config you are using? (Or, even better, is your code available publicly anywhere?).

**Comment by Sjoerd82** [comment]
Thanks for the fast reply, wasn't able to reply sooner myself. Got back to this as fast as I could, and tried some things first. I got it to work with this Quasar vite.config.js

```ts
/* eslint-env node */

/*
 * This file runs in a Node context (it's NOT transpiled by Babel), so use only
 * the ES6 features that are supported by your Node version. https://node.green/
 */

// Configuration for your app
// https://v2.quasar.dev/quasar-cli-vite/quasar-config-js
const { configure } = require('quasar/wrappers')
const path = require('path')

// Automerge WASM
const wasm = require('vite-plugin-wasm').default
const topLevelAwait = require('vite-plugin-top-level-await').default

module.exports = configure(function (/* ctx */) {
    return {
        // app boot file (/src/boot)
        // https://v2.quasar.dev/quasar-cli-vite/boot-files
        boot: [
            'axios',
        ],

        // https://v2.quasar.dev/quasar-cli-vite/quasar-config-js#css
        css: ['app.scss'],

        // https://github.com/quasarframework/quasar/tree/dev/extras
        extras: [
            'mdi-v6',
            'fontawesome-v6',
            'material-icons',
        ],

        // Full list of options: https://v2.quasar.dev/quasar-cli-vite/quasar-config-js#build
        build: {
            target: {
                browser: ['es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1'],
                node: 'node16',
            },

            vueRouterMode: 'history',

            extendViteConf(viteConf) {
                viteConf.worker = {
                    format: 'es',
                    plugins: [wasm()],
                }
                /*
                viteConf.optimizeDeps = {
                    // This is necessary because otherwise `vite dev` includes two separate
                    // versions of the JS wrapper. This causes problems because the JS
                    // wrapper has a module level variable to track JS side heap
                    // allocations, and initializing this twice causes horrible breakage
                    exclude: [
                        '@automerge/automerge-wasm',
                        '@automerge/automerge-wasm/bundler/bindgen_bg.wasm',
                        '@syntect/wasm',
                    ],
                }
                */
            },

            alias: {
                '@': path.join(__dirname, './src'),
            },

            vitePlugins: [
                [
                    topLevelAwait(),
                    wasm(),
                ],
            ],
        },

        // Full list of options: https://v2.quasar.dev/quasar-cli-vite/quasar-config-js#devServer
        devServer: {
            open: true, // opens browser window automatically
        },

        // https://v2.quasar.dev/quasar-cli-vite/quasar-config-js#framework
        framework: {
            config: {
                dark: 'auto',
            },
            // Quasar plugins
            plugins: ['Meta', 'Loading', 'LocalStorage', 'Notify', 'Dialog'],
        },

        // https://v2.quasar.dev/options/animations
        animations: ['zoomIn', 'zoomOut', 'fadeIn'],

        // https://v2.quasar.dev/quasar-cli-vite/developing-ssr/configuring-ssr
        ssr: {
            pwa: false,
            prodPort: 3000, // The default port that the production server should use
            middlewares: [
                'render', // keep this as last one
            ],
        },

        // https://v2.quasar.dev/quasar-cli-vite/developing-pwa/configuring-pwa
        pwa: {
            workboxMode: 'injectManifest',
            injectPwaMetaTags: false,
            swFilename: 'sw.js',
            manifestFilename: 'manifest.json',
            useCredentialsForManifestTag: false,
        },
    }
})
```

Now the thing that worries me is that for some reason it only works (that is to say, it didn't fail on the example) by not including the `optimizeDeps.exclude`. Yes, the thing that says that horrible thing will happen when you don't exclude them... :-)

**Comment by oleg-zaitsev** [comment]
I'm facing the same issue if I use `create-react-app` template. 
Attempts to call init or load functions cause `Uncaught TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function` error.
<details><summary>Error log</summary>
<pre>
Uncaught TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function
    at Object.create (automerge_wasm_bg.js:222:1)
    at Module.init (stable.js:84:1)
    at Module.init (next.js:57:1)
    at handle (App.js:7:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
</pre>
</details>
 
@alexjg, @Sjoerd82  were you able to find a workaround for this? 

---
Automerge ver.: 2.1.10
Create-react-app template ver.: 5.0.1
Node ver.: 10.4.0

**Comment by alexjg** [comment]
@oleg-zaitsev that is an extremely old node version, can you try with a more recent one?

**Comment by oleg-zaitsev** [comment]
Sorry for the confusion, I copied the npm version instead of the node. The version I'm using is 18.18.2
