### ISSUE TITLE
The web assembly module seems to be missing from the package

### ISSUE THREAD

**Issue by SubhoYadav** [automerge/automerge#831]
[
![Screenshot from 2023-12-24 16-06-58](https://github.com/automerge/automerge/assets/84116390/921a2b44-dbc1-404b-86c9-ea9c84427501)
](url)

**Comment by alexjg** [comment]
This looks like it's some artifact of the bundler you are using, can you post a minimal reproduction of the issue somewhere?

**Comment by SubhoYadav** [comment]
Ya sure, here are the steps to reproduce the bug
1. Create a new next app with latest nextjs version

**Comment by alexjg** [comment]
Could you put up a repo somewhere with the example you describe above? (I know it's straightforward but the less scope there is for me to misunderstand you the better).

**Comment by SubhoYadav** [comment]
Here  is the example repo

**Comment by alexjg** [comment]
Hmm, I see the problem. I had a crack at solving this by enabling the webassembly support in webpack but I run into other problems then. I'll try and have more of a look when I'm back from holidays.

For reference there's some useful stuff here: https://github.com/vercel/next.js/issues/29362

**Comment by SubhoYadav** [comment]
Thank you very much

**Comment by rohitvpatil0810** [comment]
Is this issue solved?

**Comment by HerbCaudill** [comment]
I'm running into this as well, trying to port a functioning app from vanilla React to Next.js. 

I've put up a simple repro here:
https://github.com/HerbCaudill/next-automerge-wasm

Output: 

```
> next-automerge-wasm@0.1.0 build /Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm
> next build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
   Collecting page data  .Error: ENOENT: no such file or directory, open '/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/.next/server/app/automerge_wasm_bg.wasm'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at 4 (/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/.next/server/app/page.js:7:281)
    at t (/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/.next/server/webpack-runtime.js:1:142)
    at 4689 (/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/.next/server/app/page.js:1:16734)
    at Function.t (/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/.next/server/webpack-runtime.js:1:142)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:919:21)
    at async /Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1138:17
    at async Span.traceAsyncFn (/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:151:20) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/.next/server/app/automerge_wasm_bg.wasm'
}

> Build error occurred
Error: Failed to collect page data for /
    at /Users/herbcaudill/Code/HerbCaudill/next-automerge-wasm/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1258:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  . ELIFECYCLE  Command failed with exit code 1.
```

```js
// next.config.mjs
const nextConfig = {
  webpack: function (config, options) {
    config.experiments = { asyncWebAssembly: true, layers: true }
    return config
  },
}
```

I get the same error whether or not the `config.experiments.asyncWebAssembly` flag is set.

**Comment by HerbCaudill** [comment]
When I run `pnpm dev`, I get this error:

```
### Unhandled Runtime Error

Error: Element type is invalid: expected a string (for built-in components) or a class/function
(for composite components) but got: object. You likely forgot to export your component from the
file it's defined in, or you might have mixed up default and named imports.

Check the render method of `StaticGenerationSearchParamsBailoutProvider`.

Call Stack
createFiberFromTypeAndProps
node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (27799:16)
...
```

I came across [this comment](https://github.com/vercel/next.js/issues/53163#issuecomment-1785586193) suggests that this is intended behavior:

> I don't think this is a bug. [WebAssembly instantiation is supposed to be async.](https://webassembly.github.io/esm-integration/js-api/index.html#esm-integration) In a client component, you would probably want a dynamic import and React.lazy/suspense.

Following the proposed code, I was able to get this appalling monstrosity to run:

```ts
'use client'

import { useEffect, useState } from 'react'

export default function PageComponent() {
  const [message, setMessage] = useState<string | undefined>(undefined)
  useEffect(() => {
    import('@automerge/automerge').then(({ next: A }) => {
      const foo = A.from({ message: 'Hello, world!' })
      setMessage(foo.message)
    })
  }, [])

  return <p>{message ?? 'Loading...'}</p>
}
```

I don't understand the whole "wasm has to be async" thing -- obviously, I can't be jumping through all those hoops every time I want to use Automerge, and somehow Vite manages to bundle Automerge's wasm with no issues. I suppose I could just abandon Next.js, but it is far and away the most widely used website framework for React, so I don't think Automerge can just write it off:

![image](https://github.com/automerge/automerge/assets/2136620/d1160a0b-134f-4103-a58a-e83cf244e564)


So ... I'm not sure where that leaves us.

**Comment by AL-ABYADH** [comment]
Did this issue just go completely ignored?

**Comment by lachlansleight** [comment]
Looks like it.

Obviously it's up to the developers to decide which frameworks to support (even if I personally disagree with the decision to not support by far the most popular development setup for new web projects in 2025). 

However I do feel that it would be courteous to the developer community to add a note in the public documentation somewhere to say that next.js isn't supported.

I wasted a number of hours today setting up a simple backend server + test implementation of automerge only to run into this issue when I went to test it for the first time (and then a further hour determining that it is indeed a dealbreaking issue).

**Comment by JasonKleban** [comment]
I seem to have been successful with this setup for nextjs:

```bash
$ cp ./node_modules/@automerge/automerge/dist/mjs/wasm_bindgen_output/web/automerge_wasm_bg.wasm public/automerge_wasm_bg.wasm
```

and then this mostly works ...

```
import {
  Repo,
  BroadcastChannelNetworkAdapter,
  IndexedDBStorageAdapter,
  RepoContext,
} from "@automerge/react/slim";
import * as Automerge from "@automerge/automerge/slim";

await Automerge.initializeWasm('http://localhost:3000/automerge_wasm_bg.wasm'); // <<<< This is what you copied to public/
```

... except I'm getting errors in `npm run dev` about `unhandledRejection:  ReferenceError: indexedDB is not defined` even though I specify 'use client' on line one of all the files.  So there's a recoverable error, but it seems to work besides that regarding the client side.


Note: with a <Suspense />boundary in place, this MIGHT help, but I don't actually know if it ever happens:

```
export default function MyNextComponent() {
  if (!Automerge.isWasmInitialized) { throw Automerge.wasmInitialized(); }   // <<<<<<

  const repo = React.useMemo(() =>
    new Repo({
      network: [new BroadcastChannelNetworkAdapter()],
      storage: new IndexedDBStorageAdapter(),
    }), []);
```

**Comment by laem** [comment]
Fast-forward to july 2026, I'm still getting the issue : "ENOENT: no such file or directory, open '/ROOT/cartes/node_modules/@automerge/automerge/dist/mjs/wasm_bindgen_output/nodejs/automerge_wasm_bg.wasm". 

/ROOT does not exist on my setup. 

Turbopack is default now in Next, which is still the leading framework by far.

**Comment by laem** [comment]
The problem is still here with Next@preview (1.3.0-preview.5).

**Comment by laem** [comment]
Still having the problem with next 16.3 final and Automerge 3.4. 

> ⨯ uncaughtException:  Error: ENOENT: no such file or directory, open '/ROOT/cartes/node_modules/@automerge/automerge-repo/node_modules/@automerge/automerge/dist/mjs/wasm_bindgen_output/nodejs/automerge_wasm_bg.wasm'

**Comment by laem** [comment]
OK, after one hour, I think I found the fix : https://codeberg.org/cartes/web/pulls/1754/commits/de5a34d8cb37b084bc6a6699a54925af2d33814a
