### ISSUE TITLE
WASM crash on receiving a malformed sync message

### ISSUE THREAD

**Issue by heckj** [automerge/automerge#855]
I'm working on supporting synchronization with the [automerge-repo WebSockets sync protocol](https://github.com/automerge/automerge-repo/blob/main/packages/automerge-repo-network-websocket/README.md). After successfully handshaking and receiving the `peer` message, I'm sending an initial sync message, with the content generated from a local Automerge document using [document.generateSyncMessage](https://github.com/automerge/automerge-swift/blob/c707353e7a128dda2efcfa877667c7714bcbe99e/rust/src/doc.rs#L508)

The logging in my application shows the remote side just terminating the connection. I tried with both a local instance of https://github.com/automerge/automerge-repo-sync-server.git and sync.automerge.org. I don't see the backend of sync.automerge.org, but the local instance crashed in the WASM:

```
Listening on port 3030
/Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1951
    const ret = getObject(arg0).length;
                               ^

TypeError: Cannot read properties of undefined (reading 'length')
    at module.exports.__wbg_length_1d25fa9e4ac21ce7 (/Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1951:32)
    at js_sys::Uint8Array::to_vec::hdbca7d57b40a6dd2 (wasm://wasm/00643dd6:wasm-function[1318]:0x143204)
    at automerge_wasm::decode_sync_message::he33847273875495e (wasm://wasm/00643dd6:wasm-function[203]:0xa30f3)
    at decodeSyncMessage (wasm://wasm/00643dd6:wasm-function[1235]:0x13f664)
    at module.exports.decodeSyncMessage (/Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:347:14)
    at Module.decodeSyncMessage (file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge/dist/mjs/stable.js:858:23)
    at #processSyncMessage (file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-repo/dist/synchronizer/DocSynchronizer.js:250:15)
    at #processAllPendingSyncMessages (file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-repo/dist/synchronizer/DocSynchronizer.js:285:37)
    at file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-repo/dist/synchronizer/DocSynchronizer.js:37:48

Node.js v20.3.1
```

I dumped the hex encoded raw bytes of the messages from my app:
```
Peered to targetId: 9533C6E4-8C7D-437E-BC35-4508E8616EC5 PEER[version: 1, sender: storage-server-Sparrow, target: 9533C6E4-8C7D-437E-BC35-4508E8616EC5, metadata: [storageId: d7e81eaa-f6fd-492b-ab3f-739fb0a94e52, ephemeral: false]]
SEND: SYNC[documentId: 3BwAK2fZ3Nrgn9HRBb9yvNx9xXKX, sender: 9533C6E4-8C7D-437E-BC35-4508E8616EC5, target: 9533C6E4-8C7D-437E-BC35-4508E8616EC5, data: 48 bytes]
RAW WEBSOCKET BYTES: a564747970656473796e636a646f63756d656e744964781c334277414b32665a334e72676e39485242623979764e783978584b586873656e6465724964782439353333433645342d384337442d343337452d424333352d343530384538363136454335687461726765744964782439353333433645342d384337442d343337452d424333352d3435303845383631364543356c73796e635f6d657373616765583042018a090071bde1cad843b2e87772235b520064f9f5933e4aec8d58086cb804125f00010006020a073d825600020102
SYNC MESSAGE BYTES: 42018a090071bde1cad843b2e87772235b520064f9f5933e4aec8d58086cb804125f00010006020a073d825600020102
```

I verified the initial bytes within https://cbor.me which decoded the bytes into the following:

```json
{
    "type": "sync", 
    "documentId": "3BwAK2fZ3Nrgn9HRBb9yvNx9xXKX", 
     "senderId": "9533C6E4-8C7D-437E-BC35-4508E8616EC5", 
     "targetId": "9533C6E4-8C7D-437E-BC35-4508E8616EC5", 
     "sync_message": h'42018A090071BDE1CAD843B2E87772235B520064F9F5933E4AEC8D58086CB804125F00010006020A073D825600020102'
}
```

The core the sync message I reconstituted with a python one-liner:
`echo "42018A090071BDE1CAD843B2E87772235B520064F9F5933E4AEC8D58086CB804125F00010006020A073D825600020102" | python3 -c "import sys, binascii; sys.stdout.buffer.write(binascii.unhexlify(input().strip()))" > syncmsg` - and that file is attached here as `syncmsg.zip`. (I had to compress it to make GitHub happy about accepting it)

[syncmsg.zip](https://github.com/automerge/automerge/files/14215272/syncmsg.zip)

I tried exploring what was in that message with automerge-cli: `./rust/target/debug/automerge examine-sync ~/Desktop/syncmsg`, the result of which looked "OK" to me - but I'm not familiar with the internals:

```json
{
  "changes": [],
  "have": [
    {
      "bloom": {
        "bits": [
          61,
          130,
          86
        ],
        "num_bits_per_entry": 10,
        "num_entries": 2,
        "num_probes": 7
      },
      "last_sync": []
    }
  ],
  "heads": [
    "8a090071bde1cad843b2e87772235b520064f9f5933e4aec8d58086cb804125f"
  ],
  "need": []
}
```

**Comment by heckj** [comment]
The raw bytes of the CBOR encoded sync message (as a .zip file):
[cbor_encoded_sync_msg.zip](https://github.com/automerge/automerge/files/14215576/cbor_encoded_sync_msg.zip)

**Comment by heckj** [comment]
At @acurrieclark suggestion, I tried adding some additional logging to my local instance of automerge-repo-sync (visible https://github.com/automerge/automerge-repo-sync-server/pull/6/files#diff-79f4c7cdc0b026f6e556196f5911a449157807cffdb3f9d33f0b5404b4ffc2f3)

I suspect I didn't get the code put into the correct location, as the output crashed before the additional logging could invoke:

```
yarn run v1.22.21
$ node ./src/index.js
Listening on port 3030
/Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1951
    const ret = getObject(arg0).length;
                               ^

TypeError: Cannot read properties of undefined (reading 'length')
    at module.exports.__wbg_length_1d25fa9e4ac21ce7 (/Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1951:32)
    at js_sys::Uint8Array::to_vec::hdbca7d57b40a6dd2 (wasm://wasm/00643dd6:wasm-function[1318]:0x143204)
    at automerge_wasm::decode_sync_message::he33847273875495e (wasm://wasm/00643dd6:wasm-function[203]:0xa30f3)
    at decodeSyncMessage (wasm://wasm/00643dd6:wasm-function[1235]:0x13f664)
  1 pick 23b610d local debugging
    at module.exports.decodeSyncMessage (/Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:347:14)
  1 pick c5507ce local debugging
    at Module.decodeSyncMessage (file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge/dist/mjs/stable.js:858:23)
    at #processSyncMessage (file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-repo/dist/synchronizer/DocSynchronizer.js:250:15)
    at #processAllPendingSyncMessages (file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-repo/dist/synchronizer/DocSynchronizer.js:285:37)
    at file:///Users/heckj/src/MeetingNotes/automerge-repo-sync-server/node_modules/@automerge/automerge-repo/dist/synchronizer/DocSynchronizer.js:37:48

Node.js v20.3.1
error Command failed with exit code 1.
```

**Comment by heckj** [comment]
After logging the raw messages the automerge-repo-sync-server was receiving, we spotted that I'd used the incorrect keys in the sync message. The key for the contents of the sync message should be `data`, not `sync_message` - my mistake in reading the protocol details in the CDDL documented.
