### ISSUE TITLE
undefined `context` in `import_value`

### ISSUE THREAD

**Issue by joshuahhh** [automerge/automerge#891]
Just ran into a reference to an undefined variable `context` in some Automerge code. It looks like TypeScript didn't catch it because Mocha defines "context" as a global. (I'm not good enough at TS to know how to restrict the Mocha types to test files, unfortunately.)

```
file:///.../node_modules/@automerge/automerge-repo/node_modules/@automerge/automerge/dist/mjs/proxies.js:102
            else if (isSameDocument(value, context)) {
                                           ^

ReferenceError: context is not defined
    at import_value (file:///.../node_modules/@automerge/automerge-repo/node_modules/@automerge/automerge/dist/mjs/proxies.js:102:44)
    at Object.set (file:///.../node_modules/@automerge/automerge-repo/node_modules/@automerge/automerge/dist/mjs/proxies.js:185:35)
    at <anonymous> (/.../src/server/run.ts:382:18)
    at _change (file:///.../node_modules/@automerge/automerge-repo/node_modules/@automerge/automerge/dist/mjs/stable.js:356:9)
    at Module.change (file:///.../node_modules/@automerge/automerge-repo/node_modules/@automerge/automerge/dist/mjs/stable.js:233:16)
    at callback (file:///.../node_modules/@automerge/automerge-repo/dist/DocHandle.js:301:30)
    at file:///.../node_modules/@automerge/automerge-repo/dist/DocHandle.js:152:36
    at /.../node_modules/xstate/lib/utils.js:415:23
    at Array.reduce (<anonymous>)
    at Object.updateContext (/.../node_modules/xstate/lib/utils.js:403:48)
    at handleAction (/.../node_modules/xstate/lib/actions.js:586:34)
    at processBlock (/.../node_modules/xstate/lib/actions.js:627:24)
    at Array.map (<anonymous>)
    at Object.resolveActions (/.../node_modules/xstate/lib/actions.js:652:52)
    at StateNode.resolveTransition (/.../node_modules/xstate/lib/StateNode.js:917:36)
    at StateNode.transition (/.../node_modules/xstate/lib/StateNode.js:840:17)
    at /.../node_modules/xstate/lib/interpreter.js:962:28
    at Object.provide (/.../node_modules/xstate/lib/serviceScope.js:12:16)
    at Interpreter._nextState (/.../node_modules/xstate/lib/interpreter.js:961:34)
    at /.../node_modules/xstate/lib/interpreter.js:108:31
    at Scheduler.process (/.../node_modules/xstate/lib/scheduler.js:69:7)
    at Scheduler.schedule (/.../node_modules/xstate/lib/scheduler.js:48:10)
    at Interpreter.send (/.../node_modules/xstate/lib/interpreter.js:104:23)
    at DocHandle.change (file:///.../node_modules/@automerge/automerge-repo/dist/DocHandle.js:298:23)
```

**Comment by LiraNuna** [comment]
See https://github.com/automerge/automerge/pull/932

**Comment by alexjg** [comment]
Duplicate of #914
