### ISSUE TITLE
Errors creating multiple large documents: error receiving message {   err: RuntimeError: unreachable       at __rg_oom

### ISSUE THREAD

**Issue by georgewsu** [automerge/automerge#896]
Hi, running in the following error on both sync server and client when testing with large documents.

```
error receiving message {
  err: RuntimeError: unreachable
      at __rg_oom (wasm://wasm/00664e02:wasm-function[1843]:0x156669)
      at __rust_alloc_error_handler (wasm://wasm/00664e02:wasm-function[2017]:0x1573ff)
      at alloc::alloc::handle_alloc_error::h73bbc8dacf22ba44 (wasm://wasm/00664e02:wasm-function[2082]:0x157778)
      at alloc::raw_vec::RawVec<T,A>::reserve_for_push::h5e1f145830f86d85 (wasm://wasm/00664e02:wasm-function[1133]:0x141ec7)
      at automerge::op_set::OpSetData::push::h1d8e408afe5ee7c2 (wasm://wasm/00664e02:wasm-function[546]:0x10a8be)
      at automerge::automerge::Automerge::apply_change::hf16867c0fb3a9b55 (wasm://wasm/00664e02:wasm-function[99]:0x31d63)
      at automerge::automerge::Automerge::load_with_options::hc9e89c0f3325e70b (wasm://wasm/00664e02:wasm-function[95]:0x26eb9)
      at automerge::automerge::Automerge::load_incremental_log_patches::h4635d52d0ba830a8 (wasm://wasm/00664e02:wasm-function[284]:0xcd074)
      at automerge::sync::<impl automerge::automerge::Automerge>::receive_sync_message_inner::h5cad3e1bf84132e2 (wasm://wasm/00664e02:wasm-function[110]:0x4f477)
      at <automerge::autocommit::SyncWrapper as automerge::sync::SyncDoc>::receive_sync_message::hf09a064eba627086 (wasm://wasm/00664e02:wasm-function[867]:0x1300fb)
}
```

Steps to reproduce:

Start server:
```
git clone https://github.com/automerge/automerge-repo-sync-server.git
cd automerge-repo-sync-server
npm install
npm start
```

Start client:
```
git clone https://github.com/georgewsu/automerge-client-test.git
cd automerge-client-test
git checkout error_oom
npm install
for i in {1..10}; do npm run client; done
```

The steps are similar/identical to https://github.com/automerge/automerge-repo/issues/330.

I run in to the same errors even with smaller documents (2.5 - 5MB), it just may take longer to hit it.

Here's memory usage (from the sync server node process) after creating 20 2.5MB documents.
```
memory usage:
rss: 2227.503104MB
heapTotal: 1716.862976MB
heapUsed: 1659.239216MB
external: 4275.829231MB
arrayBuffers: 25.124287MB
```

**Comment by alexjg** [comment]
If I understand correctly the test case you are running is putting 100,000 100 character strings into an array, is that correct?

**Comment by georgewsu** [comment]
> If I understand correctly the test case you are running is putting 100,000 100 character strings into an array, is that correct?

Hi, yes that is correct.

However, the error is also reproducible with other large json, for example using:
https://github.com/automerge/automerge-repo/issues/330#issuecomment-2027858477
In this case the generated json has 10,000 objects with about 20-30 fields of data in each object.

We have also reproduced with a 2.5MB json document (uncompressed unminified) with real data (proprietary).

Here's the output from my sync server, with some logging added:

```
memory usage:
rss: 2367.471616MB
heapTotal: 1717.53472MB
heapUsed: 1659.011448MB
external: 4300.419778MB
arrayBuffers: 15.900306MB

numHandlesInCache: 18
error receiving message {
  err: RuntimeError: unreachable
      at __rg_oom (wasm://wasm/00664e02:wasm-function[1843]:0x156669)
      at __rust_alloc_error_handler (wasm://wasm/00664e02:wasm-function[2017]:0x1573ff)
      at alloc::alloc::handle_alloc_error::h73bbc8dacf22ba44 (wasm://wasm/00664e02:wasm-function[2082]:0x157778)
      at alloc::raw_vec::RawVec<T,A>::reserve_for_push::h5e1f145830f86d85 (wasm://wasm/00664e02:wasm-function[1133]:0x141ec7)
      at automerge::op_set::OpSetData::push::h1d8e408afe5ee7c2 (wasm://wasm/00664e02:wasm-function[546]:0x10a8be)
      at automerge::automerge::Automerge::apply_change::hf16867c0fb3a9b55 (wasm://wasm/00664e02:wasm-function[99]:0x31d63)
      at automerge::automerge::Automerge::load_with_options::hc9e89c0f3325e70b (wasm://wasm/00664e02:wasm-function[95]:0x26eb9)
      at automerge::automerge::Automerge::load_incremental_log_patches::h4635d52d0ba830a8 (wasm://wasm/00664e02:wasm-function[284]:0xcd074)
      at automerge::sync::<impl automerge::automerge::Automerge>::receive_sync_message_inner::h5cad3e1bf84132e2 (wasm://wasm/00664e02:wasm-function[110]:0x4f477)
      at <automerge::autocommit::SyncWrapper as automerge::sync::SyncDoc>::receive_sync_message::hf09a064eba627086 (wasm://wasm/00664e02:wasm-function[867]:0x1300fb)
}
numHandlesInCache: 19
/Users/gsu/repo/cp-builder-server/node_modules/.pnpm/@automerge+automerge-wasm@0.12.0/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1990
    throw new Error(getStringFromWasm0(arg0, arg1));
    ^

Error: recursive use of an object detected which would lead to unsafe aliasing in rust
    at module.exports.__wbindgen_throw (/Users/gsu/repo/cp-builder-server/node_modules/.pnpm/@automerge+automerge-wasm@0.12.0/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1990:11)
    at wasm_bindgen::throw_str::hc0015d8a92fcec96 (wasm://wasm/00664e02:wasm-function[2065]:0x157683)
    at wasm_bindgen::__rt::borrow_fail::hd13a3345a14a3b49 (wasm://wasm/00664e02:wasm-function[2067]:0x15769f)
    at __wbg_syncstate_free (wasm://wasm/00664e02:wasm-function[1541]:0x151dff)
    at SyncStateFinalization (/Users/gsu/repo/cp-builder-server/node_modules/.pnpm/@automerge+automerge-wasm@0.12.0/node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs:1435:44)
    at FinalizationRegistry.cleanupSome (<anonymous>)

Node.js v20.12.0
 ELIFECYCLE  Command failed with exit code 1.
```

Noting that https://github.com/automerge/automerge/issues/705 looks related

**Comment by georgewsu** [comment]
To clarify, it takes multiple documents to trigger the error on the server:

```
cd automerge-client-test
git checkout file_error
 du -sh dist/data.json ; echo "should be several MB"
for i in {1..10}; do npm run client; done
```

**Comment by alexjg** [comment]
The reason this is happening is that currently automerge uses a lot of memory if you have a lot of "objects" in the document. "object" here refers to a `{}`, `[]`, or `string`. The latter is probably quite surprising, as `string` in javascript is a pretty basic type. What makes this doubly surprising is that currently our memory usage is not really related to the on disk size of the document, the on disk format is extremely compact whereas the in memory format is not.

In the medium term (think months) @orionz is working on using the same format at runtime as that which we currently use on disk, this will bring us to a predictable and small multiple of the file size for memory use.

In the short term probably the most impactful thing you can do is use `RawString` instead of `string` for fields which you don't expect to be collaborative (a better name for `RawString` would be `AtomicString` and I think we will change it's name to that in the next release).

**Comment by georgewsu** [comment]
Thanks for the answers here and in discord!

**Comment by georgewsu** [comment]
FYI, using `RawString` did help reduce the size of the memory footprint by a meaningful degree (the error is still reproducible though, it just takes longer to hit).

From the standpoint of automerge core library, confirmed that memory can be freed explicitly using:
```
        const doc = Automerge.from(largeObject)
        Automerge.free(doc)
```

From the standpoint of automerge-repo,  the cache and doc handles still have to be freed. Will continue that discussion in https://github.com/automerge/automerge-repo/issues/330.

**Comment by georgewsu** [comment]
Closing as the issue remains in automerge-repo: https://github.com/automerge/automerge-repo/issues/330 (not automerge core library)
