### ISSUE TITLE
`updateText` errors out when running commitmas example

### ISSUE THREAD

**Issue by A1Liu** [automerge/automerge#918]
## Reproduction
Tried using a modified version of the "Commitmas" example:
```js
import * as Automerge from "@automerge/automerge";

let doc1 = Automerge.from({ text: "Hello world!" });
let doc2 = Automerge.clone(doc1);
doc2 = Automerge.change(doc2, (d) => {
  Automerge.next.updateText(d, ["text"], "Goodbye world!");
});
```

Ran the above with `node test.js` .

## Outcome
Got this error:
```
file:///Users/a1liu/code/webb/node_modules/.pnpm/@automerge+automerge@2.2.1/node_modules/@automerge/automerge/dist/mjs/next.js:206
        throw new RangeError(`Cannot updateText: ${e}`);
              ^

RangeError: Cannot updateText: RangeError: invalid object ID: invalid path _root/text: path did not refer to an object
    at Module.updateText (file:///Users/a1liu/code/webb/node_modules/.pnpm/@automerge+automerge@2.2.1/node_modules/@automerge/automerge/dist/mjs/next.js:206:15)
    at file:///Users/a1liu/code/webb/native/test.js:6:18
    at _change (file:///Users/a1liu/code/webb/node_modules/.pnpm/@automerge+automerge@2.2.1/node_modules/@automerge/automerge/dist/mjs/stable.js:349:9)
    at Module.change (file:///Users/a1liu/code/webb/node_modules/.pnpm/@automerge+automerge@2.2.1/node_modules/@automerge/automerge/dist/mjs/stable.js:220:16)
    at file:///Users/a1liu/code/webb/native/test.js:5:18
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)

Node.js v18.20.0
```

## Expected Outcome
Not sure what I'm doing wrong, I thought this should work and output the information from the example.

## Environment
- Node.js v18.20.0
- `@automerge/automerge` Version: `2.2.1`
- Package manager: `pnpm`

**Comment by alexjg** [comment]
The issue here is this line:

```
import * as Automerge from "@automerge/automerge";
```

`updateText` only works with the [next API](https://automerge.org/docs/the_js_packages/#the-next-api). To use that you'll need to do something like `{ import next as Automerge} from "@automerge/automerge"` and use `Automerge.updateText` instead of `Automerge.next.updateText`. I.e. this example works for me:

```
import {next as Automerge} from "@automerge/automerge";

let doc1 = Automerge.from({ text: "Hello world!" });
let doc2 = Automerge.clone(doc1);
doc2 = Automerge.change(doc2, (d) => {
  Automerge.updateText(d, ["text"], "Goodbye world!");
});
```
